/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviecriticssystem;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author yereb
 */
public class AdultFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdultFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public AdultFrame(int userId) {
         initComponents();
    
    posterLabel.setText("No Poster");
    posterLabel.setPreferredSize(new java.awt.Dimension(150, 200));
    posterLabel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    posterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    
    loadMovies();
    loadGenres();
    
    jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int row = jTable1.getSelectedRow();
            if (row == -1) return;
            int movieId = (int) jTable1.getValueAt(row, 0);
            try (Connection conn = DatabaseConnection.connect()) {
                PreparedStatement ps = conn.prepareStatement(
                    "SELECT Poster FROM Movies WHERE MovieID = ?");
                ps.setInt(1, movieId);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) showPoster(rs.getString("Poster"));
            } catch (Exception ex) {
                posterLabel.setText("No Poster");
            }
        }
    });
    }
    
    private void showPoster(String posterPath) {
    if (posterPath == null || posterPath.isEmpty()) {
        posterLabel.setIcon(null);
        posterLabel.setText("No Poster");
        return;
    }
    
    File file = new File("posters/" + posterPath);
    if (!file.exists()) {
        posterLabel.setIcon(null);
        posterLabel.setText("No Poster");
        return;
    }
    
    ImageIcon icon = new ImageIcon(file.getAbsolutePath());
    Image scaled = icon.getImage().getScaledInstance(150, 200, Image.SCALE_SMOOTH);
    posterLabel.setIcon(new ImageIcon(scaled));
    posterLabel.setText("");
}
    
    private void loadGenres() {
    GenreFilterCombo.addItem("All");
    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT DISTINCT Genre FROM Movies")) {

        while (rs.next()) {
            GenreFilterCombo.addItem(rs.getString("Genre"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    private void loadMovies() {
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    String query = 
        "SELECT m.MovieID, m.Title, m.Genre, m.Language, m.CountryOfOrigin, m.ReleaseDate, " +
        "m.Rating, m.Watched, m.ParentalRestriction, " +
        "CONCAT(d.FirstName, ' ', d.LastName) AS Director, " +
        "CONCAT(la.FirstName, ' ', la.LastName) AS LeadingActor, " +
        "CONCAT(sa.FirstName, ' ', sa.LastName) AS SupportingActor, " +
        "m.Comments " +
        "FROM Movies m " +
        "LEFT JOIN Persons d  ON m.DirectorId = d.PersonID " +
        "LEFT JOIN Persons la ON m.LeadingActorId = la.PersonID " +
        "LEFT JOIN Persons sa ON m.SupportingActorId = sa.PersonID";

    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(query)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("MovieID"),
                rs.getString("Title"),
                rs.getString("Genre"),
                rs.getString("Language"),
                rs.getString("CountryOfOrigin"),
                rs.getDate("ReleaseDate"),
                rs.getInt("Rating"),
                rs.getBoolean("Watched"),
                rs.getBoolean("ParentalRestriction"),
                rs.getString("Director"),
                rs.getString("LeadingActor"),
                rs.getString("SupportingActor"),
                rs.getString("Comments")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddMovieButton = new javax.swing.JButton();
        DeleteMovieButton = new javax.swing.JButton();
        EdditMovieButton = new javax.swing.JButton();
        ManageUsersButton = new javax.swing.JButton();
        SetRestrictionButton = new javax.swing.JButton();
        AnalyticsButton = new javax.swing.JButton();
        ModerateContentButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        GenreFilterCombo = new javax.swing.JComboBox<>();
        ClearButton = new javax.swing.JButton();
        ViewFamilyRatingsButton = new javax.swing.JButton();
        posterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Genre", "Language", "Country", "Release Date", "Rating", "Watched", "Restriction", "Director", "Lead Actor", "Support Actor", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        AddMovieButton.setText("Add Movie");
        AddMovieButton.addActionListener(this::AddMovieButtonActionPerformed);

        DeleteMovieButton.setText("Delete Movie");
        DeleteMovieButton.addActionListener(this::DeleteMovieButtonActionPerformed);

        EdditMovieButton.setText("Edit Movie");
        EdditMovieButton.addActionListener(this::EdditMovieButtonActionPerformed);

        ManageUsersButton.setText("Manage Users");
        ManageUsersButton.addActionListener(this::ManageUsersButtonActionPerformed);

        SetRestrictionButton.setText("Set Restriction");
        SetRestrictionButton.addActionListener(this::SetRestrictionButtonActionPerformed);

        AnalyticsButton.setText("Analytics");
        AnalyticsButton.addActionListener(this::AnalyticsButtonActionPerformed);

        ModerateContentButton.setText("Moderate Content");
        ModerateContentButton.addActionListener(this::ModerateContentButtonActionPerformed);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(this::RefreshButtonActionPerformed);

        SearchButton.setText("Search");
        SearchButton.addActionListener(this::SearchButtonActionPerformed);

        ClearButton.setText("Clear");
        ClearButton.addActionListener(this::ClearButtonActionPerformed);

        ViewFamilyRatingsButton.setText("View Family Ratings");
        ViewFamilyRatingsButton.addActionListener(this::ViewFamilyRatingsButtonActionPerformed);

        posterLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(GenreFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearButton)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetRestrictionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnalyticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewFamilyRatingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModerateContentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EdditMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(posterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(GenreFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdditMovieButton)
                    .addComponent(ModerateContentButton)
                    .addComponent(SetRestrictionButton)
                    .addComponent(DeleteMovieButton)
                    .addComponent(ViewFamilyRatingsButton)
                    .addComponent(ManageUsersButton)
                    .addComponent(AddMovieButton)
                    .addComponent(AnalyticsButton)
                    .addComponent(RefreshButton))
                .addGap(54, 54, 54)
                .addComponent(posterLabel)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadMovies();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void AddMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMovieButtonActionPerformed
        this.setEnabled(false); 
     AddMovieForm form = new AddMovieForm(this);  // sadece bu satır kalmalı
     form.setVisible(true);
    }//GEN-LAST:event_AddMovieButtonActionPerformed

    private void DeleteMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMovieButtonActionPerformed
         int row = jTable1.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(this, "Select movie first");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);

    try(Connection conn = DatabaseConnection.connect()) {

        String sql = "DELETE FROM Movies WHERE MovieID = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, movieId);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Deleted!");
        loadMovies();

    } catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_DeleteMovieButtonActionPerformed

    private void EdditMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdditMovieButtonActionPerformed
     int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select movie");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);
    
    this.setEnabled(false); 
    
    EdditMovieForm form = new EdditMovieForm(movieId, this); 
    form.setVisible(true);
    }//GEN-LAST:event_EdditMovieButtonActionPerformed

    private void SetRestrictionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetRestrictionButtonActionPerformed
           int row = jTable1.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(this, "Select movie");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);

    try(Connection conn = DatabaseConnection.connect()) {

        String sql = """
            UPDATE Movies
            SET ParentalRestriction = NOT ParentalRestriction
            WHERE MovieID = ?
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, movieId);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Restriction changed");
        loadMovies();

    } catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_SetRestrictionButtonActionPerformed

    private void ManageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUsersButtonActionPerformed
        this.setEnabled(false);
     ManageUsersFrame form = new ManageUsersFrame(this);
     form.setVisible(true);
    }//GEN-LAST:event_ManageUsersButtonActionPerformed

    private void ModerateContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModerateContentButtonActionPerformed
         int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a movie first!");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);
    String movieTitle = (String) jTable1.getValueAt(row, 1);

    String[] options = {"Remove Comment", "Remove Rating", "Remove Both", "Cancel"};
    int choice = JOptionPane.showOptionDialog(this,
        "What do you want to moderate for: " + movieTitle,
        "Moderate Content",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.WARNING_MESSAGE,
        null, options, options[0]);

    if (choice == 3 || choice == -1) return;

    String sql;
    if (choice == 0) {
        sql = "UPDATE Movies SET Comments = NULL WHERE MovieID = ?";
    } else if (choice == 1) {
        sql = "UPDATE Movies SET Rating = 0 WHERE MovieID = ?";
    } else {
        sql = "UPDATE Movies SET Comments = NULL, Rating = 0 WHERE MovieID = ?";
    }

    try (Connection conn = DatabaseConnection.connect()) {
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, movieId);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Done!");
        loadMovies();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_ModerateContentButtonActionPerformed

    private void AnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButtonActionPerformed
       try (Connection conn = DatabaseConnection.connect()) {

        Statement stmt = conn.createStatement();


        ResultSet rs1 = stmt.executeQuery("SELECT COUNT(*) as total FROM Movies");
        int total = 0;
        if (rs1.next()) total = rs1.getInt("total");


        ResultSet rs2 = stmt.executeQuery("SELECT COUNT(*) as watched FROM Movies WHERE Watched = TRUE");
        int watched = 0;
        if (rs2.next()) watched = rs2.getInt("watched");


        ResultSet rs3 = stmt.executeQuery("SELECT AVG(Rating) as avg FROM Movies");
        double avg = 0;
        if (rs3.next()) avg = rs3.getDouble("avg");


        ResultSet rs4 = stmt.executeQuery("SELECT Title, Rating FROM Movies ORDER BY Rating DESC LIMIT 1");
        String topTitle = "-";
        int topRating = 0;
        if (rs4.next()) {
            topTitle = rs4.getString("Title");
            topRating = rs4.getInt("Rating");
        }


        String message =  "Total Movies     : " + total + "\n" + "Watched Movies   : " + watched + "\n" + "Unwatched Movies : " + (total - watched) + "\n" + "Average Rating   : " + String.format("%.1f", avg) + "\n" + "Top Rated Movie  : " + topTitle + " (" + topRating + "/10)";
         JOptionPane.showMessageDialog(this, message, "Analytics", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_AnalyticsButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
      String keyword = SearchTextField.getText().trim();
    String genre = (String) GenreFilterCombo.getSelectedItem();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    String sql = "SELECT MovieID, Title, Genre, Language, ReleaseDate, Rating, Watched, ParentalRestriction, Comments FROM Movies WHERE 1=1";

    if (!keyword.isEmpty()) {
        sql += " AND (Title LIKE '%" + keyword + "%' OR Language LIKE '%" + keyword + "%')";
    }

    if (genre != null && !genre.equals("All")) {
        sql += " AND Genre = '" + genre + "'";
    }

    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            Object[] row = {
                rs.getInt("MovieID"),
                rs.getString("Title"),
                rs.getString("Genre"),
                rs.getString("Language"),
                rs.getDate("ReleaseDate"),
                rs.getInt("Rating"),
                rs.getBoolean("Watched"),
                rs.getBoolean("ParentalRestriction"),
                rs.getString("Comments")
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
    SearchTextField.setText("");
    GenreFilterCombo.setSelectedIndex(0);
    loadMovies();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ViewFamilyRatingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFamilyRatingsButtonActionPerformed
       int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a movie first!");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);
    String movieTitle = (String) jTable1.getValueAt(row, 1);

    try (Connection conn = DatabaseConnection.connect()) {
        PreparedStatement ps = conn.prepareStatement(
            "SELECT u.Username, i.Rating, i.Comment " +
            "FROM UserMovieInteractions i " +
            "JOIN Users u ON i.UserID = u.UserId " +
            "WHERE i.MovieID = ?");
        ps.setInt(1, movieId);
        ResultSet rs = ps.executeQuery();

        StringBuilder sb = new StringBuilder(movieTitle + "\n\n");
        boolean hasData = false;
        while (rs.next()) {
            hasData = true;
            sb.append(rs.getString("Username")).append("\n");
            sb.append("Rating: ").append(rs.getObject("Rating") != null ? rs.getInt("Rating") + "/10" : "-").append("\n");
            sb.append("Comment: ").append(rs.getString("Comment") != null ? rs.getString("Comment") : "-").append("\n\n");
        }
        if (!hasData) sb.append("No ratings or comments yet.");

        JOptionPane.showMessageDialog(this, sb.toString(), "Family Ratings", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_ViewFamilyRatingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdultFrame(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMovieButton;
    private javax.swing.JButton AnalyticsButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteMovieButton;
    private javax.swing.JButton EdditMovieButton;
    private javax.swing.JComboBox<String> GenreFilterCombo;
    private javax.swing.JButton ManageUsersButton;
    private javax.swing.JButton ModerateContentButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton SetRestrictionButton;
    private javax.swing.JButton ViewFamilyRatingsButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel posterLabel;
    // End of variables declaration//GEN-END:variables
}
