/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviecriticssystem;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author yereb
 */
public class ChildFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChildFrame.class.getName());
    private int userId;
    /**
     * Creates new form ChildFrame
     */

public ChildFrame(int userId) {
    this.userId = userId; 
    initComponents();
    loadMovies();
    loadGenres();
}

private void loadMovies() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    String sql = "SELECT MovieID, Title, Genre, Language, ReleaseDate, Rating, Watched, Comments FROM Movies WHERE ParentalRestriction = FALSE";

    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            Object[] row = {
                rs.getInt("MovieID"),
                rs.getString("Title"),
                rs.getString("Genre"),
                rs.getString("Language"),
                rs.getDate("ReleaseDate"),
                rs.getInt("Rating"),
                rs.getBoolean("Watched"),
                rs.getString("Comments")
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    
}

private void upsertInteraction(int movieId, String field, Object value) {
    try (Connection conn = DatabaseConnection.connect()) {
        PreparedStatement check = conn.prepareStatement(
            "SELECT InteractionID FROM UserMovieInteractions WHERE UserID=? AND MovieID=?");
        check.setInt(1, userId);
        check.setInt(2, movieId);
        ResultSet rs = check.executeQuery();

        if (rs.next()) {
            PreparedStatement upd = conn.prepareStatement(
                "UPDATE UserMovieInteractions SET " + field + "=? WHERE UserID=? AND MovieID=?");
            if (value instanceof Integer) upd.setInt(1, (Integer) value);
            else if (value instanceof Boolean) upd.setBoolean(1, (Boolean) value);
            else upd.setString(1, (String) value);
            upd.setInt(2, userId);
            upd.setInt(3, movieId);
            upd.executeUpdate();
        } else {
            PreparedStatement ins = conn.prepareStatement(
                "INSERT INTO UserMovieInteractions (UserID, MovieID, " + field + ") VALUES (?,?,?)");
            ins.setInt(1, userId);
            ins.setInt(2, movieId);
            if (value instanceof Integer) ins.setInt(3, (Integer) value);
            else if (value instanceof Boolean) ins.setBoolean(3, (Boolean) value);
            else ins.setString(3, (String) value);
            ins.executeUpdate();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void loadGenres() {
    GenreFilterCombo.addItem("All");
    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT DISTINCT Genre FROM Movies WHERE ParentalRestriction = FALSE")) {

        while (rs.next()) {
            GenreFilterCombo.addItem(rs.getString("Genre"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MarkWatchedButton = new javax.swing.JButton();
        RateMovieButton = new javax.swing.JButton();
        AddCommentButton = new javax.swing.JButton();
        WatchlistButton = new javax.swing.JButton();
        ProgressButton = new javax.swing.JButton();
        FamilyRatingsButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        GenreFilterCombo = new javax.swing.JComboBox<>();
        SearchTextField = new javax.swing.JTextField();
        SearchButton1 = new javax.swing.JButton();
        ClearButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Genre", "Language", "Release Date", "Rating", "Watched", "Comments"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        MarkWatchedButton.setText("Mark Watched");
        MarkWatchedButton.addActionListener(this::MarkWatchedButtonActionPerformed);

        RateMovieButton.setText("Rate Movie");
        RateMovieButton.addActionListener(this::RateMovieButtonActionPerformed);

        AddCommentButton.setText("Add Comment");
        AddCommentButton.addActionListener(this::AddCommentButtonActionPerformed);

        WatchlistButton.setText("My Watchlist");
        WatchlistButton.addActionListener(this::WatchlistButtonActionPerformed);

        ProgressButton.setText("My Progress");
        ProgressButton.addActionListener(this::ProgressButtonActionPerformed);

        FamilyRatingsButton.setText("Family Ratings");
        FamilyRatingsButton.addActionListener(this::FamilyRatingsButtonActionPerformed);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(this::RefreshButtonActionPerformed);

        SearchButton1.setText("Search");
        SearchButton1.addActionListener(this::SearchButton1ActionPerformed);

        ClearButton1.setText("Clear");
        ClearButton1.addActionListener(this::ClearButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(GenreFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearButton1)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MarkWatchedButton)
                    .addComponent(FamilyRatingsButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(RateMovieButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RefreshButton)
                            .addComponent(AddCommentButton))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ProgressButton))
                    .addComponent(WatchlistButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton1)
                    .addComponent(GenreFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WatchlistButton)
                    .addComponent(RateMovieButton)
                    .addComponent(MarkWatchedButton))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FamilyRatingsButton)
                    .addComponent(AddCommentButton)
                    .addComponent(ProgressButton))
                .addGap(18, 18, 18)
                .addComponent(RefreshButton)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        String keyword = SearchTextField.getText().trim();
    String genre = (String) GenreFilterCombo.getSelectedItem();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    String sql = "SELECT MovieID, Title, Genre, Language, ReleaseDate, Rating, Watched, Comments FROM Movies WHERE ParentalRestriction = FALSE";

    if (!keyword.isEmpty()) {
        sql += " AND (Title LIKE '%" + keyword + "%' OR Language LIKE '%" + keyword + "%')";
    }
    if (genre != null && !genre.equals("All")) {
        sql += " AND Genre = '" + genre + "'";
    }

    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("MovieID"),
                rs.getString("Title"),
                rs.getString("Genre"),
                rs.getString("Language"),
                rs.getDate("ReleaseDate"),
                rs.getInt("Rating"),
                rs.getBoolean("Watched"),
                rs.getString("Comments")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_SearchButton1ActionPerformed

    private void ClearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButton1ActionPerformed
    SearchTextField.setText("");
    GenreFilterCombo.setSelectedIndex(0);
    loadMovies();
    }//GEN-LAST:event_ClearButton1ActionPerformed

    private void MarkWatchedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkWatchedButtonActionPerformed
          int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a movie first!");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);

    upsertInteraction(movieId, "Watched", true);
    JOptionPane.showMessageDialog(this, "Marked as watched!");
    loadMovies();
    }//GEN-LAST:event_MarkWatchedButtonActionPerformed

    private void RateMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateMovieButtonActionPerformed
           int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a movie first!");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);

    String input = JOptionPane.showInputDialog(this, "Enter rating (1-10):");
    if (input == null || input.trim().isEmpty()) return;

    int score;
    try {
        score = Integer.parseInt(input.trim());
        if (score < 1 || score > 10) {
            JOptionPane.showMessageDialog(this, "Rating must be between 1-10!");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid number!");
        return;
    }

    upsertInteraction(movieId, "Rating", score);
    JOptionPane.showMessageDialog(this, "Rating saved!");
    loadMovies();
    }//GEN-LAST:event_RateMovieButtonActionPerformed

    private void AddCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCommentButtonActionPerformed
            int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a movie first!");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);

    String comment = JOptionPane.showInputDialog(this, "Enter your comment:");
    if (comment == null || comment.trim().isEmpty()) return;

        upsertInteraction(movieId, "Comment", comment.trim());
        JOptionPane.showMessageDialog(this, "Comment added!");
        loadMovies();   
    }//GEN-LAST:event_AddCommentButtonActionPerformed

    private void ProgressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgressButtonActionPerformed
      try (Connection conn = DatabaseConnection.connect()) {

        PreparedStatement ps1 = conn.prepareStatement(
            "SELECT COUNT(*) as total FROM Movies WHERE ParentalRestriction = FALSE");
        ResultSet rs1 = ps1.executeQuery();
        int total = rs1.next() ? rs1.getInt("total") : 0;


        PreparedStatement ps2 = conn.prepareStatement(
            "SELECT COUNT(*) as watched FROM UserMovieInteractions " +
            "WHERE UserID = ? AND Watched = TRUE");
        ps2.setInt(1, userId);
        ResultSet rs2 = ps2.executeQuery();
        int watched = rs2.next() ? rs2.getInt("watched") : 0;

        String message =
            "Total Available Movies : " + total + "\n" +
            "You Watched            : " + watched + "\n" +
            "Remaining              : " + (total - watched);

        JOptionPane.showMessageDialog(this, message,
                "My Progress", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_ProgressButtonActionPerformed

    private void FamilyRatingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamilyRatingsButtonActionPerformed
       int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a movie first!");
        return;
    }

    int movieId = (int) jTable1.getValueAt(row, 0);
    String movieTitle = (String) jTable1.getValueAt(row, 1);

    try (Connection conn = DatabaseConnection.connect()) {
        PreparedStatement ps = conn.prepareStatement(
            "SELECT u.Username, i.Rating, i.Comment " +
            "FROM UserMovieInteractions i " +
            "JOIN Users u ON i.UserID = u.UserId " +
            "WHERE i.MovieID = ?");
        ps.setInt(1, movieId);
        ResultSet rs = ps.executeQuery();

        StringBuilder sb = new StringBuilder(movieTitle + "\n\n");
        boolean hasData = false;
        while (rs.next()) {
            hasData = true;
            sb.append(rs.getString("Username")).append("\n");
            sb.append("Rating: ").append(rs.getObject("Rating") != null ? rs.getInt("Rating") + "/10" : "-").append("\n");
            sb.append("Comment: ").append(rs.getString("Comment") != null ? rs.getString("Comment") : "-").append("\n\n");
        }
        if (!hasData) sb.append("No ratings or comments yet.");

        JOptionPane.showMessageDialog(this, sb.toString(), "Family Ratings", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_FamilyRatingsButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadMovies();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void WatchlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatchlistButtonActionPerformed
         try (Connection conn = DatabaseConnection.connect()) {
        String sql = """
            SELECT m.Title, m.Genre, m.Rating
            FROM Movies m
            WHERE m.ParentalRestriction = FALSE
            AND m.MovieID NOT IN (
                SELECT MovieID FROM UserMovieInteractions
                WHERE UserID = ? AND Watched = TRUE
            )
            ORDER BY m.Title
        """;
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, userId);
        ResultSet rs = ps.executeQuery();

        StringBuilder sb = new StringBuilder("My Watchlist (Not Watched Yet):\n\n");
        boolean hasMovies = false;
        while (rs.next()) {
            sb.append("• ").append(rs.getString("Title"))
              .append(" (").append(rs.getString("Genre")).append(")")
              .append(" - Rating: ").append(rs.getInt("Rating")).append("/10\n");
            hasMovies = true;
        }
        if (!hasMovies) sb.append("You've watched everything! 🎉");

        JOptionPane.showMessageDialog(this, sb.toString(),
                "My Watchlist", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_WatchlistButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChildFrame(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCommentButton;
    private javax.swing.JButton ClearButton1;
    private javax.swing.JButton FamilyRatingsButton;
    private javax.swing.JComboBox<String> GenreFilterCombo;
    private javax.swing.JButton MarkWatchedButton;
    private javax.swing.JButton ProgressButton;
    private javax.swing.JButton RateMovieButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SearchButton1;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton WatchlistButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
