/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviecriticssystem;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author yereb
 */
public class EdditMovieForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EdditMovieForm.class.getName());
    private int movieId;
    /**
     * Creates new form AddMovieForm
     */
private java.awt.Frame parentFrame;

public EdditMovieForm(int movieId, java.awt.Frame parent) {
    initComponents();
    this.movieId = movieId;
    this.parentFrame = parent;
    loadPersonsToCombo();
    loadMovieData();
    // form kapanınca parent'ı tekrar aç
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            parentFrame.setEnabled(true);
            parentFrame.toFront();
        }
    });
}   private void loadPersonsToCombo() {

    directorCombo.addItem("-- Select --");
    leadingActorCombo.addItem("-- Select --");
    supportingActorCombo.addItem("-- Select --");

    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(
             "SELECT PersonID, FirstName, LastName FROM Persons ORDER BY FirstName")) {

        while (rs.next()) {
            String item = rs.getInt("PersonID") + " - " +
                          rs.getString("FirstName") + " " +
                          rs.getString("LastName");
            directorCombo.addItem(item);
            leadingActorCombo.addItem(item);
            supportingActorCombo.addItem(item);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading persons: " + e.getMessage());
    }
}
       private Integer getSelectedPersonId(javax.swing.JComboBox<String> combo) {
    String selected = (String) combo.getSelectedItem();
    if (selected == null || selected.startsWith("--")) return null;
    try {
        return Integer.parseInt(selected.split(" - ")[0].trim());
    } catch (NumberFormatException e) {
        return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleText = new javax.swing.JLabel();
        GenreText = new javax.swing.JLabel();
        LanguageText = new javax.swing.JLabel();
        ReleaseDateText = new javax.swing.JLabel();
        RatingText = new javax.swing.JLabel();
        AboutText = new javax.swing.JLabel();
        CommentsText = new javax.swing.JLabel();
        TitleTextField = new javax.swing.JTextField();
        GenreTextField = new javax.swing.JTextField();
        LanguageTextField = new javax.swing.JTextField();
        ReleaseDateTextField = new javax.swing.JTextField();
        RatingTextField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        restrictionCheckBox = new javax.swing.JCheckBox();
        Scroll = new javax.swing.JScrollPane();
        aboutArea = new javax.swing.JTextArea();
        Scroll2 = new javax.swing.JScrollPane();
        commentsArea = new javax.swing.JTextArea();
        supportingActorCombo = new javax.swing.JComboBox<>();
        RatingText1 = new javax.swing.JLabel();
        ReleaseDateText1 = new javax.swing.JLabel();
        leadingActorCombo = new javax.swing.JComboBox<>();
        directorCombo = new javax.swing.JComboBox<>();
        LanguageText1 = new javax.swing.JLabel();
        GenreText1 = new javax.swing.JLabel();
        PosterTextField = new javax.swing.JTextField();
        CountryTextField = new javax.swing.JTextField();
        TitleText1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitleText.setText("Title :");

        GenreText.setText("Genre :");

        LanguageText.setText("Language:");

        ReleaseDateText.setText("ReleaseDate:");

        RatingText.setText("Rating :");

        AboutText.setText("About :");

        CommentsText.setText("Comments :");

        SaveButton.setText("Save");
        SaveButton.addActionListener(this::SaveButtonActionPerformed);

        restrictionCheckBox.setText("ParentalRestriction");
        restrictionCheckBox.addActionListener(this::restrictionCheckBoxActionPerformed);

        aboutArea.setColumns(20);
        aboutArea.setRows(5);
        Scroll.setViewportView(aboutArea);

        commentsArea.setColumns(20);
        commentsArea.setRows(5);
        Scroll2.setViewportView(commentsArea);

        RatingText1.setText("Support Actor :");

        ReleaseDateText1.setText("Lead Actor :");

        LanguageText1.setText("Director :");

        GenreText1.setText("Poster :");

        TitleText1.setText("Country :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RatingText)
                            .addComponent(ReleaseDateText)
                            .addComponent(LanguageText)
                            .addComponent(GenreText)
                            .addComponent(TitleText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LanguageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RatingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReleaseDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CommentsText)
                                    .addComponent(AboutText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Scroll2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(restrictionCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(SaveButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RatingText1)
                            .addComponent(ReleaseDateText1)
                            .addComponent(LanguageText1)
                            .addComponent(GenreText1)
                            .addComponent(TitleText1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PosterTextField)
                            .addComponent(directorCombo, 0, 111, Short.MAX_VALUE)
                            .addComponent(leadingActorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CountryTextField)
                            .addComponent(supportingActorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleText)
                    .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenreText)
                    .addComponent(GenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LanguageText)
                    .addComponent(LanguageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReleaseDateText)
                    .addComponent(ReleaseDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingText)
                    .addComponent(RatingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleText1)
                    .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenreText1)
                    .addComponent(PosterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LanguageText1)
                    .addComponent(directorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReleaseDateText1)
                    .addComponent(leadingActorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingText1)
                    .addComponent(supportingActorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(AboutText)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Scroll2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(CommentsText)))
                .addGap(18, 18, 18)
                .addComponent(restrictionCheckBox)
                .addGap(36, 36, 36)
                .addComponent(SaveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadMovieData() {
    try (Connection conn = DatabaseConnection.connect()) {

        String sql = "SELECT * FROM Movies WHERE MovieID = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, movieId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            TitleTextField.setText(rs.getString("Title"));
            GenreTextField.setText(rs.getString("Genre"));
            LanguageTextField.setText(rs.getString("Language"));
            ReleaseDateTextField.setText(rs.getDate("ReleaseDate").toString());
            RatingTextField.setText(String.valueOf(rs.getInt("Rating")));
            aboutArea.setText(rs.getString("About"));
            commentsArea.setText(rs.getString("Comments"));
            restrictionCheckBox.setSelected(rs.getBoolean("ParentalRestriction"));
            CountryTextField.setText(rs.getString("CountryOfOrigin") != null ? rs.getString("CountryOfOrigin") : "");
            PosterTextField.setText(rs.getString("Poster") != null ? rs.getString("Poster") : "");

            // ComboBox seçimlerini ayarla
            selectComboById(directorCombo,        rs.getObject("DirectorId"));
            selectComboById(leadingActorCombo,    rs.getObject("LeadingActorId"));
            selectComboById(supportingActorCombo, rs.getObject("SupportingActorId"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void selectComboById(javax.swing.JComboBox<String> combo, Object id) {
    if (id == null) return;
    String prefix = id.toString() + " - ";
    for (int i = 0; i < combo.getItemCount(); i++) {
        if (combo.getItemAt(i).startsWith(prefix)) {
            combo.setSelectedIndex(i);
            return;
        }
    }
}
    
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
String title = TitleTextField.getText().trim();
String genre = GenreTextField.getText().trim();
String language = LanguageTextField.getText().trim();
String about = aboutArea.getText().trim();
String comments = commentsArea.getText().trim();
String country  = CountryTextField.getText().trim();
String poster   = PosterTextField.getText().trim();
Integer directorId  = getSelectedPersonId(directorCombo);
Integer leadActorId = getSelectedPersonId(leadingActorCombo);
Integer suppActorId = getSelectedPersonId(supportingActorCombo);

// --- TITLE ---
if (title.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Title boş olamaz!");
    return;
}

// --- GENRE ---
if (genre.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Genre boş olamaz!");
    return;
}

// --- LANGUAGE ---
if (language.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Language boş olamaz!");
    return;
}

// --- RELEASE DATE ---
java.sql.Date releaseDate;
try {
    releaseDate = java.sql.Date.valueOf(ReleaseDateTextField.getText().trim());
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "ReleaseDate yanlış format! (YYYY-MM-DD)");
    return;
}

// --- RATING ---
int rating;
try {
    rating = Integer.parseInt(RatingTextField.getText().trim());

    if (rating < 1 || rating > 10) {
        JOptionPane.showMessageDialog(this, "Rating 1 ile 10 arasında olmalı!");
        return;
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Rating sayı olmalı!");
    return;
}

// --- RESTRICTION ---
boolean restriction = restrictionCheckBox.isSelected();

// --- UPDATE ---
try (Connection conn = DatabaseConnection.connect()) {

        String sql = """
            UPDATE Movies
            SET Title=?, Genre=?, Language=?, CountryOfOrigin=?,
                ReleaseDate=?, Rating=?, ParentalRestriction=?,
                About=?, Comments=?, Poster=?,
                DirectorId=?, LeadingActorId=?, SupportingActorId=?
            WHERE MovieID=?
        """;

    PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, title);
        ps.setString(2, genre);
        ps.setString(3, language);
        ps.setString(4, country.isEmpty() ? null : country);
        ps.setDate(5, releaseDate);
        ps.setInt(6, rating);
        ps.setBoolean(7, restriction);
        ps.setString(8, about);
        ps.setString(9, comments);
        ps.setString(10, poster.isEmpty() ? null : poster);

        if (directorId  != null) ps.setInt(11, directorId);
        else ps.setNull(11, java.sql.Types.INTEGER);

        if (leadActorId != null) ps.setInt(12, leadActorId);
        else ps.setNull(12, java.sql.Types.INTEGER);

        if (suppActorId != null) ps.setInt(13, suppActorId);
        else ps.setNull(13, java.sql.Types.INTEGER);

        ps.setInt(14, movieId);

    ps.executeUpdate();

    JOptionPane.showMessageDialog(this, "Movie Updated!");
    this.dispose();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
}
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void restrictionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restrictionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restrictionCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutText;
    private javax.swing.JLabel CommentsText;
    private javax.swing.JTextField CountryTextField;
    private javax.swing.JLabel GenreText;
    private javax.swing.JLabel GenreText1;
    private javax.swing.JTextField GenreTextField;
    private javax.swing.JLabel LanguageText;
    private javax.swing.JLabel LanguageText1;
    private javax.swing.JTextField LanguageTextField;
    private javax.swing.JTextField PosterTextField;
    private javax.swing.JLabel RatingText;
    private javax.swing.JLabel RatingText1;
    private javax.swing.JTextField RatingTextField;
    private javax.swing.JLabel ReleaseDateText;
    private javax.swing.JLabel ReleaseDateText1;
    private javax.swing.JTextField ReleaseDateTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JScrollPane Scroll2;
    private javax.swing.JLabel TitleText;
    private javax.swing.JLabel TitleText1;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.JTextArea aboutArea;
    private javax.swing.JTextArea commentsArea;
    private javax.swing.JComboBox<String> directorCombo;
    private javax.swing.JComboBox<String> leadingActorCombo;
    private javax.swing.JCheckBox restrictionCheckBox;
    private javax.swing.JComboBox<String> supportingActorCombo;
    // End of variables declaration//GEN-END:variables
}
