/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviecriticssystem;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author yereb
 */
public class ManageUsersFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageUsersFrame.class.getName());

    /**
     * Creates new form ManageUsersFrame
     */
    private java.awt.Frame parentFrame;

    public ManageUsersFrame(java.awt.Frame parent) {
        initComponents();
        this.parentFrame = parent;
        loadUsers();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                parentFrame.setEnabled(true);
                parentFrame.toFront();
            }
        });
    }

    private void loadUsers() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try (Connection conn = DatabaseConnection.connect();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT UserId, Username, Email, UserType FROM Users")) {

            while (rs.next()) {
                String typeLabel = rs.getInt("UserType") == 1 ? "Adult" : "Child";
                model.addRow(new Object[]{
                    rs.getInt("UserId"),
                    rs.getString("Username"),
                    rs.getString("Email"),
                    typeLabel
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddUserButton = new javax.swing.JButton();
        DeleteUserButton = new javax.swing.JButton();
        ResetPasswordButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UserID", "Username", "Email", "UserType "
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        AddUserButton.setText("Add User");
        AddUserButton.addActionListener(this::AddUserButtonActionPerformed);

        DeleteUserButton.setText("Delete User");
        DeleteUserButton.addActionListener(this::DeleteUserButtonActionPerformed);

        ResetPasswordButton.setText("Reset Password");
        ResetPasswordButton.addActionListener(this::ResetPasswordButtonActionPerformed);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(this::RefreshButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(AddUserButton)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteUserButton)
                        .addGap(105, 105, 105)
                        .addComponent(ResetPasswordButton)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUserButton)
                    .addComponent(DeleteUserButton)
                    .addComponent(ResetPasswordButton))
                .addGap(26, 26, 26)
                .addComponent(RefreshButton)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtonActionPerformed
         String username = JOptionPane.showInputDialog(this, "Username:");
        if (username == null || username.trim().isEmpty()) return;

        String password = JOptionPane.showInputDialog(this, "Password:");
        if (password == null || password.trim().isEmpty()) return;

        String email = JOptionPane.showInputDialog(this, "Email:");
        if (email == null || email.trim().isEmpty()) return;

        String[] types = {"Adult", "Child"};
        int choice = JOptionPane.showOptionDialog(this, "User Type:", "Select Type",
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, types, types[0]);
        if (choice == -1) return;
        int userType = (choice == 0) ? 1 : 2;

        try (Connection conn = DatabaseConnection.connect()) {
            String sql = "INSERT INTO Users (UserId, Username, Password, UserType, Email) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setNull(1, java.sql.Types.INTEGER);
            ps.setString(2, username.trim());
            ps.setString(3, password.trim());
            ps.setInt(4, userType);
            ps.setString(5, email.trim());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "User created!");
            loadUsers();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_AddUserButtonActionPerformed

    private void DeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserButtonActionPerformed
         int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first!");
            return;
        }

        int userId = (int) jTable1.getValueAt(row, 0);
        String username = (String) jTable1.getValueAt(row, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete user '" + username + "'?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try (Connection conn = DatabaseConnection.connect()) {
            PreparedStatement ps = conn.prepareStatement("DELETE FROM Users WHERE UserId = ?");
            ps.setInt(1, userId);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "User deleted!");
            loadUsers();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_DeleteUserButtonActionPerformed

    private void ResetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswordButtonActionPerformed
         int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first!");
            return;
        }

        int userId = (int) jTable1.getValueAt(row, 0);
        String username = (String) jTable1.getValueAt(row, 1);

        String newPass = JOptionPane.showInputDialog(this, "New password for '" + username + "':");
        if (newPass == null || newPass.trim().isEmpty()) return;

        try (Connection conn = DatabaseConnection.connect()) {
            PreparedStatement ps = conn.prepareStatement("UPDATE Users SET Password = ? WHERE UserId = ?");
            ps.setString(1, newPass.trim());
            ps.setInt(2, userId);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Password reset!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_ResetPasswordButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadUsers();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserButton;
    private javax.swing.JButton DeleteUserButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton ResetPasswordButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
