

public class ModerationFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModerationFrame.class.getName());

    /**
     * Creates new form ModerationFrame
     */
private java.awt.Frame parentFrame;

public ModerationFrame(java.awt.Frame parent) {
    initComponents();
    this.parentFrame = parent;
    loadInteractions();
    Theme.applyToSub(this);
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            parentFrame.setEnabled(true);
            parentFrame.toFront();
        }
    });
    
}

private void loadInteractions() {
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    String sql = "SELECT i.InteractionID, u.Username, m.Title, i.Rating, i.Comment, i.Status " +
                 "FROM UserMovieInteractions i " +
                 "JOIN Users u ON i.UserID = u.UserId " +
                 "JOIN Movies m ON i.MovieID = m.MovieID " +
                 "ORDER BY FIELD(i.Status,'pending','approved','rejected')";

    try (java.sql.Connection conn = DatabaseConnection.connect();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("InteractionID"),
                rs.getString("Username"),
                rs.getString("Title"),
                rs.getObject("Rating") != null ? rs.getInt("Rating") + "/10" : "-",
                rs.getString("Comment") != null ? rs.getString("Comment") : "-",
                rs.getString("Status")
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void updateStatus(String newStatus) {
    int row = jTable1.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row first!");
        return;
    }

    int interactionId = (int) jTable1.getValueAt(row, 0);

    try (java.sql.Connection conn = DatabaseConnection.connect()) {
        java.sql.PreparedStatement ps = conn.prepareStatement(
            "UPDATE UserMovieInteractions SET Status = ? WHERE InteractionID = ?");
        ps.setString(1, newStatus);
        ps.setInt(2, interactionId);
        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Status updated to: " + newStatus.toUpperCase());
        loadInteractions();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttons = new javax.swing.JPanel();
        ApproveButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();
        Tables = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Buttons.setLayout(new java.awt.GridLayout(1, 0));

        ApproveButton.setText("Approve");
        ApproveButton.addActionListener(this::ApproveButtonActionPerformed);
        Buttons.add(ApproveButton);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(this::RefreshButtonActionPerformed);
        Buttons.add(RefreshButton);

        RejectButton.setText("Reject");
        RejectButton.addActionListener(this::RejectButtonActionPerformed);
        Buttons.add(RejectButton);

        getContentPane().add(Buttons, java.awt.BorderLayout.CENTER);

        Tables.setPreferredSize(new java.awt.Dimension(500, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "InteractionID ", "Username", "Movie Title", "Rating", "Comment", "Status"
            }
        ));
        Tables.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(Tables, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadInteractions();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void ApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveButtonActionPerformed
        updateStatus("approved");
    }//GEN-LAST:event_ApproveButtonActionPerformed

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        updateStatus("rejected");
    }//GEN-LAST:event_RejectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ModerationFrame(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveButton;
    private javax.swing.JPanel Buttons;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton RejectButton;
    private javax.swing.JScrollPane Tables;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
